# Generated by Django 5.2 on 2025-04-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDoSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='DDoS protection triggered', max_length=255)),
                ('request_count', models.IntegerField(default=0)),
            ],
        ),
    ]
