# Generated by Django 5.2 on 2025-05-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widgetlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='widgets.widget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
