# Generated by Django 5.2 on 2025-05-04 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_alter_widgetlog_options_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='widgets.widget'),
        ),
    ]
